name: richardbrunt.co.uk
permalink: /:categories/:title/
author: Richard Brunt
plugins:
  - jekyll-feed
# feed:
#   categories:
#     - blog
#   posts_limit: 10
#   excerpt_only: true
prose:
  siteurl: 'http://richardbrunt.co.uk/'